// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Warehouse.DAL;

namespace Warehouse.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Warehouse.DAL.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomenclatureCode")
                        .IsRequired();

                    b.Property<string>("PartName")
                        .IsRequired();

                    b.Property<DateTime>("ProductionDate");

                    b.Property<double>("Quantity");

                    b.Property<DateTime?>("RemovalDate");

                    b.Property<bool>("Special");

                    b.Property<int>("StoreKeeperId");

                    b.HasKey("PartId");

                    b.HasIndex("StoreKeeperId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Warehouse.DAL.StoreKeeper", b =>
                {
                    b.Property<int>("StoreKeeperId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("StoreKeeperId");

                    b.ToTable("StoreKeepers");
                });

            modelBuilder.Entity("Warehouse.DAL.Part", b =>
                {
                    b.HasOne("Warehouse.DAL.StoreKeeper", "StoreKeeper")
                        .WithMany("Parts")
                        .HasForeignKey("StoreKeeperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
